package:
  name: pyxrf
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  number: 0

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

  entry_points:
    - pyxrf = pyxrf.gui:run

requirements:
  build:
    - python
    - enaml [py2k]
    - numpy
    - six

  run:
    - python
    - matplotlib
    - pyyaml
    - enaml [py2k]
    - six

test:
  imports:
    - pyxrf [py2k]
