package:
  name: pyxrf
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}
  entry_points:
    - pyxrf = pyxrf.gui:run

requirements:
  build:
    - python
    - setuptools

  run:
    - enaml
    - h5py
    - matplotlib
    - numpy
    - pandas
    - python
    - scikit-beam

about:
  home: http://github.com/NSLS-II/pyxrf
  license: 3-Clause BSD
