package:
  name: pyxrf
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../


build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

requirements:
  build:
    - python
    - distribute
    - numpy
    - six
    - matplotlib
  run:
    - python
    - numpy
    - matplotlib
    - pyqt
    - six

test:
  requires:
    - nose

  imports:
    - pyxrf
    - pyxrf.qt_widgets
    - pyxrf.messenger
    - pyxrf.messenger.mpl
    - pyxrf.backend
    - pyxrf.backend.mpl


about:
  home: https://github.com/Nikea/pyxrf
  license: 3-Clause BSD
